name: "PROD DEPLOY"

on:
    push:
      branches:
        - main
  
permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: prod
            aws-assume-role-arn: "arn:aws:iam::262630072804:role/GitHubActionsPipeline"
            aws-region: "us-east-2"
            aws-statefile-s3-bucket: "corbanez97-terraform-statefile"
            aws-lock-dynamodb-table: "corbanez97-terraform-lock"